apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pipejet-ui-4cc090d2-2c86-4ab5-881a-18d2aa37873a-certificate
  namespace: pipejet-ui-4cc090d2-2c86-4ab5-881a-18d2aa37873a
spec:
  secretName: pipejet-ui-4cc090d2-2c86-4ab5-881a-18d2aa37873a-secret-tls
  commonName: sovannlyna-pipejet-ui.assessify.org
  dnsNames:
  - sovannlyna-pipejet-ui.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
